services:
  - type: web
    name: purapasion-backend
    runtime: docker
    plan: free
    region: ohio
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
